package com.customallchat;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;
import net.runelite.client.config.ConfigSection;

@ConfigGroup("customallchat")
public interface CustomAllChatConfig extends Config
{
	@ConfigItem(
			keyName = "messagePrefix",
			name = "Message Prefix",
			description = "Prefix added to all sent messages."
	)

	default String messagePrefix() { return ""; }

	/* Sources generated by the game itself. This includes chat messages from - Quests, skilling, items, NPCs, scripts, etc. */
	@ConfigSection(
			name = "Game Sources",
			description = "Settings for chat messages created by player origins",
			position = 0,
			closedByDefault = false
	)

	String gameSourceSettings = "gameSourceSettings";

	@ConfigItem(
		keyName = "gameMessage",
		name = "Game Messages",
		description = "Messages generated by game sources.",
		section = gameSourceSettings
	)

	default boolean gameMessage() { return true; }

	@ConfigItem(
			keyName = "engineMessage",
			name = "Engine Messages",
			description = "Messages generated by game engine.",
			section = gameSourceSettings
	)

	default boolean engineMessage() { return true; }

	@ConfigItem(
			keyName = "broadcastMessage",
			name = "Broadcast Messages",
			description = "Messages generated by broadcasts.",
			section = gameSourceSettings
	)

	default boolean broadcastMessage() { return true; }

	@ConfigItem(
			keyName = "snapshotMessage",
			name = "Snapshot Messages",
			description = "Messages generated by abuse report submissions.",
			section = gameSourceSettings
	)

	default boolean snapshotMessage() { return true; }

	@ConfigItem(
			keyName = "examineMessage",
			name = "Examine Messages",
			description = "Messages generated by examining an item.",
			section = gameSourceSettings
	)

	default boolean examineMessage() { return true; }

	@ConfigItem(
			keyName = "npcExamineMessage",
			name = "NPC Examine Messages",
			description = "Messages generated by examining a non-player character.",
			section = gameSourceSettings
	)

	default boolean npcExamineMessage() { return true; }

	@ConfigItem(
			keyName = "objectExamineMessage",
			name = "Object Examine Messages",
			description = "Messages generated by examining an object.",
			section = gameSourceSettings
	)

	default boolean objectExamineMessage() { return true; }

	@ConfigItem(
			keyName = "clanSystemMessage",
			name = "Clan System Messages",
			description = "Messages generated by an action or notification within a clan setting.",
			section = gameSourceSettings
	)

	default boolean clanSystemMessage() { return true; }

	@ConfigItem(
			keyName = "consoleMessage",
			name = "Console Messages",
			description = "Messages generated by changing a setting.",
			section = gameSourceSettings
	)

	default boolean consoleMessage() { return true; }

	@ConfigItem(
			keyName = "playerMessage",
			name = "Player Messages",
			description = "Messages relating to the player.",
			section = gameSourceSettings
	)

	default boolean playerMessage() { return true; }

	/* Sources generated by players. This includes chat messages from - public, friend, clan, mod, etc. */
	@ConfigSection(
			name = "Player Sources",
			description = "Settings for chat messages created by player origins",
			position = 1,
			closedByDefault = false
	)

	String playerSourceSettings = "playerSourceSettings";

	@ConfigItem(
			keyName = "modMessage",
			name = "Mod Messages",
			description = "Messages in public chat by a moderator.",
			section = playerSourceSettings
	)

	default boolean modMessage() { return true; }

	@ConfigItem(
			keyName = "modPrivateMessage",
			name = "Mod Private Messages",
			description = "Messages in private chat by a moderator.",
			section = playerSourceSettings
	)

	default boolean modPrivateMessage() { return true; }

	@ConfigItem(
			keyName = "publicMessage",
			name = "Public Messages",
			description = "Messages in public chat by another player.",
			section = playerSourceSettings
	)

	default boolean publicMessage() { return true; }

	@ConfigItem(
			keyName = "privateMessage",
			name = "Private Messages",
			description = "Messages in private chat by another player.",
			section = playerSourceSettings
	)

	default boolean privateMessage() { return true; }

	@ConfigItem(
			keyName = "sentPrivateMessage",
			name = "Sent Private Messages",
			description = "Messages in private chat sent by yourself.",
			section = playerSourceSettings
	)

	default boolean sentPrivateMessage() { return true; }

	@ConfigItem(
			keyName = "logMessage",
			name = "Log Messages",
			description = "Messages generated when a friend logs in or out.",
			section = playerSourceSettings
	)

	default boolean logMessage() { return true; }

	@ConfigItem(
			keyName = "friendsMessage",
			name = "Friends Messages",
			description = "Messages received in friends chat.",
			section = playerSourceSettings
	)

	default boolean friendsMessage() { return true; }

	@ConfigItem(
			keyName = "friendsNotificationMessage",
			name = "Friends Notification Messages",
			description = "Messages received with information about the current friends chat.",
			section = playerSourceSettings
	)

	default boolean friendsNotificationMessage() { return true; }

	@ConfigItem(
			keyName = "tradeSentMessage",
			name = "Trade Sent Messages",
			description = "Messages generated upon sending a trade request.",
			section = playerSourceSettings
	)

	default boolean tradeSentMessage() { return true; }

	@ConfigItem(
			keyName = "tradeMessage",
			name = "Trade Messages",
			description = "Messages generated upon receiving a trade request.",
			section = playerSourceSettings
	)

	default boolean tradeMessage() { return true; }

	@ConfigItem(
			keyName = "duelMessage",
			name = "Duel Messages",
			description = "Messages generated upon receiving a duel request.",
			section = playerSourceSettings
	)

	default boolean duelMessage() { return true; }

	@ConfigItem(
			keyName = "duelSentMessage",
			name = "Duel Sent Messages",
			description = "Messages generated upon receiving a duel request.",
			section = playerSourceSettings
	)

	default boolean duelSentMessage() { return true; }

	@ConfigItem(
			keyName = "duelTradeCompleteMessage",
			name = "Duel Trade Complete Messages",
			description = "Messages generated upon completing a duel or trade.",
			section = playerSourceSettings
	)

	default boolean duelTradeCompleteMessage() { return true; }

	@ConfigItem(
			keyName = "friendListMessage",
			name = "Friend List Messages",
			description = "Messages generated upon adding a player to a friend list.",
			section = playerSourceSettings
	)

	default boolean friendListMessage() { return true; }

	@ConfigItem(
			keyName = "ignoreListMessage",
			name = "Ignore List Messages",
			description = "Messages generated upon adding a player to a ignore list.",
			section = playerSourceSettings
	)

	default boolean ignoreListMessage() { return true; }

	@ConfigItem(
			keyName = "clanMessage",
			name = "Clan Messages",
			description = "Messages received in a clan chat.",
			section = playerSourceSettings
	)

	default boolean clanMessage() { return true; }

	@ConfigItem(
			keyName = "clanGuestMessage",
			name = "Clan Guest Messages",
			description = "Messages received in a guest clan chat.",
			section = playerSourceSettings
	)

	default boolean clanGuestMessage() { return true; }

	@ConfigItem(
			keyName = "autoMessage",
			name = "Auto Messages",
			description = "Autotyper Messages received in a public chat.",
			section = playerSourceSettings
	)

	default boolean autoMessage() { return true; }


	@ConfigItem(
			keyName = "autoModMessage",
			name = "Auto Mod Messages",
			description = "Autotyper Messages received my a moderator.",
			section = playerSourceSettings
	)

	default boolean autoModMessage() { return true; }

}
